import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useQuery, useMutation } from '../convex/_generated/react'
import { useCallback } from 'react'

const Home: NextPage = () => {
  const messages = useQuery('getChat') ?? []
  const addChatMessage = useMutation('addChatMessage')

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js with Convex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js</a> with{' '}
          <a href="https://convex.dev">Convex</a>
        </h1>

        <div className={styles.chatLog}>
          {messages.map((msg: any) => (
            <p>
              <span className={styles.author}>{msg.author}</span>
              <span className={styles.message}>{msg.message}</span>
            </p>
          ))}
        </div>

        <form
          className={styles.chat}
          onSubmit={(event) => {
            event.preventDefault()

            const data = new FormData(event.currentTarget)

            const newMessage = {
              author: data.get('name') as string,
              message: data.get('message') as string,
            }

            if (!newMessage.author || !newMessage.message) {
              return
            }

            addChatMessage(newMessage)
          }}
        >
          <label htmlFor="name">Name</label>
          <input id="name" name="name" type="text" />

          <label htmlFor="message">Message</label>
          <textarea id="message" name="message"></textarea>

          <button type="submit">Send Message</button>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.convex.dev/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/convex.svg" alt="Convex Logo" width={90} height={18} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
